Tliter/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'twitter.views.index'),
    url(r'^tweets/', include('twitter.urls', namespace='twitter')),
    url(r'^logout/', 'twitter.views.logout_view', name='logout'),
    url(r'^login/', 'twitter.views.login_view', name='login'),
    url(r'^register/', 'twitter.views.register_view', name='register'),
)

twitter/urls.py
from django.conf.urls import patterns, url

from twitter import views

urlpatterns = patterns('',
    url(r'^(?P<tweet_id>\d+)/$', views.show_tweet, name='show_tweet'),
    url(r'^by/(?P<username>\w+)/$', views.tweets_by, name='tweets_by'),
    url(r'^add/$', views.add, name='add'),
    url(r'^$', views.index, name='index'),
)

twitter/models.py
from django.db import models
from django.contrib.auth.models import User

class Tweet(models.Model):
	message = models.TextField(blank=False)
	pub_date = models.DateTimeField('date published',blank=False)
	hashtags = models.ManyToManyField('HashTag')
	author = models.ForeignKey(User)
	
	def __unicode__(self):
		return self.message
	
class HashTag(models.Model):
	name = models.CharField(max_length=200,blank=False,unique=True)
	
	def __unicode__(self):
		return 'haszTag' + self.name

twitter/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.contrib.auth import authenticate, logout, login
from django.core.urlresolvers import reverse
from django.contrib import messages

from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from twitter.models import Tweet

def getTweetsPage(request, tweets):
    paginator = Paginator(tweets, 7) # Show per page

    page = request.GET.get('page')
    try:
        res = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        res = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        res = paginator.page(paginator.num_pages)

    return res

def display_tweets(request, tweets, can_add):
	context = {'tweets': tweets, 'can_tweet' : can_add and request.user.is_authenticated()}
	return render(request, 'twitter/show_tweets.html', context)

def index(request):
	latest_tweets = getTweetsPage(request, Tweet.objects.order_by('-pub_date'))
	return display_tweets(request, latest_tweets, True) #FIXME: can_add depending on login 

def show_tweet(request, tweet_id):
	out = None
	try:
		t = get_object_or_404(Tweet, id=tweet_id)
		out = display_tweets(request, {t}, False)
	except Tweet.DoesNotExist:
		out = HttpResponse("Tweet %s nonexistent" % tweet_id)
		
	return out

def tweets_by(request, username):
	out = None
	try:
		u = get_object_or_404(User, username=username)
		tweets = getTweetsPage(request, Tweet.objects.filter(author=u).order_by('-pub_date'))
		out = display_tweets(request, tweets, False)
	except Tweet.DoesNotExist:
		out = HttpResponse("Wrong input")
	return out

def add(request):
	t = Tweet(message=request.POST['message'], pub_date=timezone.now(), author=request.user)
	t.save()
	return HttpResponseRedirect(reverse('twitter:index'))

def login_view(request):
	username = request.POST['username'] if 'username' in request.POST else '';
	password = request.POST['password'] if 'password' in request.POST else '';

	if not password or not username:
		messages.add_message(request, messages.ERROR, 'Błąd! Musisz wypełnić wszystkie pola!' )
	else:
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
		else:
			messages.add_message(request, messages.ERROR, 'Użyszkodnik nie istnieje!')
	
	return HttpResponseRedirect(reverse('twitter:index'))

def logout_view(request):
	logout(request)
	messages.add_message(request, messages.INFO, 'Wylogowano.')
	return HttpResponseRedirect(reverse('twitter:index'))

def show_registration(request, usernameCallback=None):
	return render(request, 'twitter/register.html', {'can_register' : not request.user.is_authenticated(), 'username' : usernameCallback})

def register_view(request):
	if 'post' in request.POST:
		#TODO IN!
		username = request.POST['username'] if 'username' in request.POST else '';
		password = request.POST['password'] if 'password' in request.POST else '';
	
		error = False
	
		if username and User.objects.filter(username=username).count():
			error = True
			messages.add_message(request, messages.ERROR, 'Błąd! Użyszkodnik o takiej nazwie już istnieje!')
			
		if not password or not username:
			error = True
			messages.add_message(request, messages.ERROR, 'Błąd! Musisz wypełnić wszystkie pola!' )
		
		if error:
			return show_registration(request, username)
		
		User.objects.create_user(username=username, password=password)
		messages.add_message(request, messages.INFO, 'Pomyślnie utworzono użyszkodnika.')
		return login_view(request)
	else:
		return render(request, 'twitter/register.html',  {'can_register' : not request.user.is_authenticated()})

twitter/templates/twitter/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Tłiter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{{STATIC_URL}}js/jquery-1.8.3.js" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body style=' background-color: lightgray;'>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tłiter</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            </ul>
            
            {% if user.is_authenticated %}
		<div class="pull-right">
			<ul class="nav">
				<li class="navbar-text">Zalogowany jako {{ user.username }} &nbsp;</li>
			</ul>
			<a class="btn btn-mini" href="{% url 'logout' %}">wyloguj</a>
		</div>
		{% else %}
			<form class="navbar-form pull-right" action="{% url 'login' %}" method="post">
				{% csrf_token %}
				<input type="text" name="username"/>
				<input type="password" name="password"/>
				<input class="btn" type="submit" value="Zaloguj"/>
				<a class="btn" href="{% url 'register' %}">Rejestracja</a>
			</form>
		{% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <!-- <a class="close" data-dismiss="alert">TODO someday: ×</a> -->
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="container">
	{% block content %}{% endblock %}
    </div> <!-- /container -->
  </body>
</html>

twitter/templates/twitter/register.html
{% extends "twitter/base.html" %}
{% block content %}
	{% if can_register %}
		<form class="form-horizontal span4 offset3" style="font-align: center" method="POST" href="{% url 'register' %}">
			{% csrf_token %}
			<input type="hidden" name="post" value="1"/>
			<div class="control-group">
				<label class="control-label" for="username">Nazwa użyszkodnika</label>
				<div class="controls">
					<input type="text" name="username" value="{{ username }}"/>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="password">Haseło</label>
				<div class="controls">
					<input type="password" name="password"/>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input type="submit" class="btn" value="Rejestruj!"/>
				</div>
			</div>
		</form>
	{% else %}
		Jesteś już zarejestrowany!
	{% endif %}
{% endblock %}

twitter/templates/twitter/show_tweets.html
{% extends "twitter/base.html" %}
{%block content %}
	{% if tweets %}
		{% for t in tweets %}
			<div class="container-fluid" style="padding-bottom: 20px;">
				<div class="span7 offset2" style="background-color: lightblue; border: solid 1px black;">
					<div class="row-fluid" style="background-color: gray; min-height: 30px;">
						<div class="span1">
							<a style="color: lightgray; font-weight: bold; text-decoration: none;" href="{% url 'twitter:show_tweet' t.id %}">#{{ t.id }}</a>
						</div>
						<div class="span5 text-left">
							{{ t.pub_date|date:"d M Y" }} użytkownik 
							<a style="color: black; font-weight: bold; text-decoration: none;" href="{% url 'twitter:tweets_by' t.author.username %}">
							{{ t.author.username }}</a> tłitnął:
						</div>
					</div>
					<div class "row-fluid" style="min-height: 40px;">
						<div class="span7">
							{{ t.message }}
						</div>
					</div>
					{% if t.hashtags.all %}
						<div class="row-fluid" style="background-color: lightgray">
							<div class="span7">
								{{ t.hashtags.all | join:", " }}
							</div>
						</div>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	{% else %}
		<p>No tweets are available.</p>
	{% endif %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<ul class="pager span3 offset4" style="font-align: center; padding: 0px;">
		{% if tweets.has_previous %}
			<li><a href="?page={{ tweets.previous_page_number }}">&laquo;</a></li>
		{% endif %}

			<li><a href="#">{{ tweets.number }}</a></li>
		
		{% if tweets.has_next %}
			<li><a href="?page={{ tweets.next_page_number }}">&raquo;</a></li>
		{% endif %}
	</ul>
	
	{% if can_tweet %}
		<form class="span6 offset3 text-center" action="{% url 'twitter:add'%}" style="padding-top: 3px;" method="post">
			{% csrf_token %}
			<textarea name="message" style="width: 80%; height: 100px;"></textarea>
			<input type="submit" class="btn btn-primary" value="Tłitnij!"/>
		</form>
	{% endif %}
	
</div>
	
{%endblock%}